import Foundation
import Testing
@testable import AgentBeaconCore

@Test func detectorFindsCliFromPathAndBundledAppExecutable() throws {
    let fixture = try IntegrationFixture()
    try fixture.makeExecutable("bin/codex")
    try fixture.makeExecutable("Applications/Cursor.app/Contents/Resources/app/bin/cursor")

    let detector = AgentDetector(
        executableSearchPaths: [fixture.path("bin")],
        applicationSearchPaths: [fixture.path("Applications")],
        shimDirectoryURL: fixture.url("shims"),
        shellProfileURL: fixture.url(".zshrc")
    )

    let results = detector.detect()
    let codex = try #require(results.first { $0.definition.platform == .codex })
    let cursor = try #require(results.first { $0.definition.platform == .cursor })

    #expect(codex.cliPath == fixture.path("bin/codex"))
    #expect(cursor.cliPath == fixture.path("Applications/Cursor.app/Contents/Resources/app/bin/cursor"))
    #expect(cursor.appPath == fixture.path("Applications/Cursor.app"))
}

@Test func detectorSkipsExistingAgentBeaconShimsInPath() throws {
    let fixture = try IntegrationFixture()
    try fixture.makeExecutable(
        "old-shims/claude",
        contents: """
        #!/usr/bin/env bash
        # Generated by Agent Beacon. Edit with: AgentBeaconStatus connect
        exit 0
        """
    )
    try fixture.makeExecutable("real-bin/claude")

    let detector = AgentDetector(
        executableSearchPaths: [fixture.path("old-shims"), fixture.path("real-bin")],
        applicationSearchPaths: [fixture.path("Applications")],
        shimDirectoryURL: fixture.url("new-shims"),
        shellProfileURL: fixture.url(".zshrc")
    )

    let claude = try #require(detector.detect().first { $0.definition.platform == .claudeCode })
    #expect(claude.cliPath == fixture.path("real-bin/claude"))
}

@Test func shimInstallerWritesExecutableShimThatCallsRealAgentThroughRunner() throws {
    let fixture = try IntegrationFixture()
    try fixture.makeExecutable("bin/codex")
    try fixture.makeExecutable("bin/agent-beacon-run")

    let detector = AgentDetector(
        executableSearchPaths: [fixture.path("bin")],
        applicationSearchPaths: [fixture.path("Applications")],
        shimDirectoryURL: fixture.url("shims"),
        shellProfileURL: fixture.url(".zshrc")
    )
    let codex = try #require(detector.detect().first { $0.definition.platform == .codex })
    let installer = AgentShimInstaller(
        shimDirectoryURL: fixture.url("shims"),
        runnerURL: fixture.url("bin/agent-beacon-run")
    )

    let shims = try installer.installShims(for: [codex])
    let shim = try #require(shims.first)
    let script = try String(contentsOf: URL(fileURLWithPath: shim.shimPath), encoding: .utf8)

    #expect(FileManager.default.isExecutableFile(atPath: shim.shimPath))
    #expect(script.contains("--platform 'codex'"))
    #expect(script.contains("-- \"$REAL_AGENT\" \"$@\""))
    #expect(script.contains("bin/codex"))
}

@Test func generatedShimExecutesRunnerWithDefaultPath() throws {
    let fixture = try IntegrationFixture()
    try fixture.makeExecutable("bin/codex")
    let runnerURL = fixture.url("bin/agent-beacon-run")
    let argsURL = fixture.url("runner-args.txt")
    try fixture.makeExecutable(
        "bin/agent-beacon-run",
        contents: """
        #!/usr/bin/env bash
        printf '%s\\n' "$@" > '\(argsURL.path)'
        """
    )

    let detector = AgentDetector(
        executableSearchPaths: [fixture.path("bin")],
        applicationSearchPaths: [fixture.path("Applications")],
        shimDirectoryURL: fixture.url("shims"),
        shellProfileURL: fixture.url(".zshrc")
    )
    let codex = try #require(detector.detect().first { $0.definition.platform == .codex })
    let installer = AgentShimInstaller(
        shimDirectoryURL: fixture.url("shims"),
        runnerURL: runnerURL
    )
    let shim = try #require(try installer.installShims(for: [codex]).first)

    let process = Process()
    process.executableURL = URL(fileURLWithPath: shim.shimPath)
    process.arguments = ["--version"]
    try process.run()
    process.waitUntilExit()

    let args = try String(contentsOf: argsURL, encoding: .utf8)
    #expect(process.terminationStatus == 0)
    #expect(args.contains("--platform"))
    #expect(args.contains("codex"))
    #expect(args.contains(fixture.path("bin/codex")))
    #expect(args.contains("--version"))
}

@Test func shellProfileInstallerAddsShimPathOnce() throws {
    let fixture = try IntegrationFixture()
    let installer = ShellProfileInstaller(
        shimDirectoryURL: fixture.url("shims"),
        shellProfileURL: fixture.url(".zshrc")
    )

    let first = try installer.ensureShimDirectoryIsFirstInPath()
    let second = try installer.ensureShimDirectoryIsFirstInPath()
    let profile = try String(contentsOf: fixture.url(".zshrc"), encoding: .utf8)

    #expect(first == true)
    #expect(second == false)
    #expect(profile.components(separatedBy: ShellProfileInstaller.beginMarker).count == 2)
    #expect(profile.contains("export PATH=\"\(fixture.path("shims")):$PATH\""))
}

private struct IntegrationFixture {
    let root: URL

    init() throws {
        root = FileManager.default.temporaryDirectory
            .appendingPathComponent("AgentBeaconTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    }

    func url(_ relativePath: String) -> URL {
        root.appendingPathComponent(relativePath)
    }

    func path(_ relativePath: String) -> String {
        url(relativePath).path
    }

    func makeExecutable(
        _ relativePath: String,
        contents: String = "#!/usr/bin/env bash\nexit 0\n"
    ) throws {
        let url = url(relativePath)
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try contents.write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
    }
}
